"""
Combine XLSX files (one per subject) with lesion metrics generated by SCT's sct_analyze_lesion into a single CSV file
for easier manipulation and visualization.

Namely, the script:
 - reads XLSX files (located under /results) with lesion metrics computed by SCT's sct_analyze_lesion
    (one XLSX file per subject)
 - fetches the lesion metrics (such as lesion volume, etc.) from the XLSX files
 - aggregates the metrics across subjects into a single dataframe and save the dataframe to a CSV file

Example usage:
    python 02_combine_xlsx_files.py -input-folder <DIR_NAME>/results -o <DIR_NAME>/results/lesion_metrics_all_subjects.csv -pred-type manual_lesion_manual_cord
    python 02_combine_xlsx_files.py -input-folder <DIR_NAME>/results -o <DIR_NAME>/results/lesion_metrics_all_subjects.csv -pred-type manual_lesion_scisegv2_cord
    python 02_combine_xlsx_files.py -input-folder <DIR_NAME>/results -o <DIR_NAME>/results/lesion_metrics_all_subjects.csv -pred-type scisegv2_lesion_scisegv2_cord

Note: to read XLSX files, you might need to install the following packages:
    pip install openpyxl

Author: Jan Valosek
"""

import os
import re
import glob
import argparse

import pandas as pd


def get_parser():
    """
    parser function
    """

    parser = argparse.ArgumentParser(
        description='Read XLSX files (located under /results) with lesion metrics (computed using sct_analyze_lesion),'
                    'construct a dataframe, and save the dataframe to a CSV file'
                    'The aggregated lesion metrics will be saved to a CSV file in -ofolder.',
        prog=os.path.basename(__file__).strip('.py')
    )
    parser.add_argument(
        '-input-folder',
        metavar='DIR_NAME',
        required=True,
        type=str,
        help='Absolute path to the \'results\' folder with XLSX files generated using \'sct_analyze_lesion. '
             'The results folders were generated using the \'01_compute_midsagittal_lesion_measures.sh\' '
             'script.'
    )
    parser.add_argument(
        '-pred-type',
        required=True,
        type=str,
        choices=['manual_lesion_manual_cord', 'manual_lesion_scisegv2_cord', 'scisegv2_lesion_scisegv2_cord'],
        help='Type of the predicted lesion:'
             'manual_lesion_manual_cord: manual lesion, manual cord, '
             'manual_lesion_scisegv2_cord: manual lesion, SCIsegV2 cord, '
             'scisegv2_lesion_scisegv2_cord: SCIsegV2 lesion, SCIsegV2 cord, '
             'This information will be included in the output CSV filename.'
    )
    parser.add_argument(
        '-o',
        metavar='DIR_NAME',
        required=True,
        type=str,
        help='Path to the output folder where the CSV file with aggregated lesion metrics will be saved.'
             'Example: \'<YOUR_PATH>/results/\'. The output CSV file will be named '
             '\'lesion_metrics_all_subjects_<pred_type>.csv\', where <pred_type>'
    )

    return parser


def fetch_subject(filename_path):
    """
    Get subject ID and session ID from the input BIDS-compatible filename or file path
    The function works both on absolute file path as well as filename
    :param filename_path: input nifti filename (e.g., sub-001_ses-01_T1w.nii.gz) or file path
    (e.g., /home/user/MRI/bids/derivatives/labels/sub-001/ses-01/anat/sub-001_ses-01_T1w.nii.gz
    :return: subject_session: subject ID (e.g., sub-001)
    :return: sessionID: session ID (e.g., ses-01)
    """

    subject = re.search('sub-(.*?)[_/]', filename_path)     # [_/] means either underscore or slash
    subjectID = subject.group(0)[:-1] if subject else ""    # [:-1] removes the last underscore or slash

    session = re.search('ses-(.*?)[_/]', filename_path)     # [_/] means either underscore or slash
    sessionID = session.group(0)[:-1] if session else ""    # [:-1] removes the last underscore or slash

    # REGEX explanation
    # . - match any character (except newline)
    # *? - match the previous element as few times as possible (zero or more times)

    return subjectID, sessionID


def get_fnames(dir_path, pred_type):
    """
    Get list of XLSX files with lesion metrics
    :param dir_path: list of paths to XLSX files with lesion metrics
    :param pred_type: manual_lesion_manual_cord or manual_lesion_scisegv2_cord or scisegv2_lesion_scisegv2_cord
    :return: pandas dataframe with the paths to the XLSX files
    """

    # Get XLSX files with lesion metrics
    if pred_type == 'manual_lesion_manual_cord':
        fname_files = glob.glob(os.path.join(dir_path, '*manual_lesion_manual_cord.xlsx'))
    elif pred_type == 'manual_lesion_scisegv2_cord':
        fname_files = glob.glob(os.path.join(dir_path, '*manual_lesion_scisegv2_cord.xlsx'))
    elif pred_type == 'scisegv2_lesion_scisegv2_cord':
        fname_files = glob.glob(os.path.join(dir_path, '*scisegv2_lesion_scisegv2_cord.xlsx'))

    # remove hidden files starting with '~'
    fname_files = [f for f in fname_files if not os.path.basename(f).startswith('~')]
    # if fname_files is empty, exit
    if len(fname_files) == 0:
        print(f'ERROR: No XLSX files found in {dir_path}')

    # Sort the list of file names (to make the list the same when provided the input folders in different order)
    fname_files.sort()
    df = pd.DataFrame({'fname': fname_files})

    # Add a column with participant_id and session_id
    df['participant_id'] = df['fname'].apply(lambda x: fetch_subject(x)[0])
    df['session_id'] = df['fname'].apply(lambda x: fetch_subject(x)[1])
    print(f'Number of participants: {len(df)}')

    return df


def fetch_lesion_metrics(index, row, df):
    """
    Fetch lesion metrics from the XLSX file with lesion metrics generated by sct_analyze_lesion
    :param index: index of the dataframe
    :param row: row of the dataframe (one row corresponds to one participant)
    :param df: dataframe with the paths to the XLSX files for manual and predicted lesions
    :return: df: updated dataframe with the paths to the XLSX files for manual and predicted lesions and lesion metrics
    """

    # Check if the XLSX file exists
    if not os.path.exists(row['fname']):
        raise ValueError(f"ERROR: {row['fname']} does not exist.")

    # Read the XLSX file with lesion metrics
    df_lesion = pd.read_excel(row['fname'], sheet_name='measures')
    if len(df_lesion) > 1:
        print(f'Subject: {row["participant_id"]} has more than one lesion. Aggregating the metrics across lesions.')

    # Save the values in the currently processed df row
    df.at[index, f'number_of_lesions'] = int(len(df_lesion))
    # Sum volume and length across all lesions
    df.at[index, 'volume'] = df_lesion['volume [mm3]'].sum()
    df.at[index, 'length'] = df_lesion['length [mm]'].sum()
    df.at[index, 'length_interpolated_midsagittal_slice'] = df_lesion['length_interpolated_midsagittal_slice [mm]'].sum()
    # Take max width across all lesions
    df.at[index, 'width'] = df_lesion['width [mm]'].max()
    df.at[index, 'width_interpolated_midsagittal_slice'] = df_lesion['width_interpolated_midsagittal_slice [mm]'].max()

    # Take minimum tissue bridge across all lesions
    df.at[index, 'interpolated_dorsal_bridge_width'] = df_lesion['interpolated_dorsal_bridge_width [mm]'].min()
    df.at[index, 'interpolated_ventral_bridge_width'] = df_lesion['interpolated_ventral_bridge_width [mm]'].min()
    df.at[index, 'interpolated_total_bridge_width'] = df_lesion['interpolated_total_bridge_width [mm]'].max()

    # Tissue bridge ratios -- compute it from the minimum tissue bridge widths
    total_bridge_width = (df.at[index, 'interpolated_dorsal_bridge_width'] +
                          df.at[index, 'interpolated_ventral_bridge_width'])
    df.at[index, 'dorsal_bridge_ratio'] = df.at[index, 'interpolated_dorsal_bridge_width'] / total_bridge_width * 100 if total_bridge_width > 0 else 0
    df.at[index, 'ventral_bridge_ratio'] = df.at[index, 'interpolated_ventral_bridge_width'] / total_bridge_width * 100 if total_bridge_width > 0 else 0

    return df


def main():
    # Parse the command line arguments
    parser = get_parser()
    args = parser.parse_args()

    pred_type = args.pred_type

    # Check if the input path exists
    path_input = os.path.abspath(os.path.expanduser(args.input_folder))
    if not os.path.exists(path_input):
        raise ValueError(f'ERROR: {path_input} does not exist.')

    # For each participant_id, get XLSX files with lesion metrics
    df = get_fnames(path_input, pred_type)

    # Iterate over the rows of the dataframe and read the XLSX files
    for index, row in df.iterrows():
        print(f'Processing XLSX files for {row["participant_id"]}')
        # Read the XLSX file with lesion metrics
        df = fetch_lesion_metrics(index, row, df)

    # Remove column containing the paths to the XLSX files (we don't need it anymore)
    df.drop(columns=[f'fname'], inplace=True)

    # Save the dataframe with lesion metrics to a CSV file
    dir_out = os.path.abspath(os.path.expanduser(args.o))
    if not os.path.exists(dir_out):
        os.makedirs(dir_out)
        print(f'Created output folder: {dir_out}')
    fname_out = os.path.join(dir_out, f'lesion_metrics_all_subjects_{pred_type}.csv')
    df.to_csv(fname_out, index=False)
    print(f'Saved lesion metrics to {fname_out}')


if __name__ == '__main__':
    main()
